 # third OR in this regex will match more than valid IPv4s,
 # but is more readable, maybe more performant and it should not matter
 # it matches one to three digits in each octet, separated by dots,
 # so 001.000.000.0 is an "IP" as well as 999.999.999.999

 # note IPv6 is not matched

if ( $host !~* "^(${NGINX_HOST}|www.${NGINX_HOST}|(\d{1,3}\.){3}\d{1,3})$" ) {
    return 444;
}
