[supervisord]
nodaemon=true
user=root

[program:metrics]
command=uv run /root/serve_metrics.py
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:cron]
command=/bin/bash -c "printenv > /etc/environment && /usr/sbin/cron -f"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0