#cloud-config
groups:
  - docker

system_info:
  default_user:
    groups: [docker]

write_files:
  - path: /home/ubuntu/installer.sh
    permissions: '0755'
    content: |
      apt-get clean && apt-get update && apt-get install -y ca-certificates curl gnupg lsb-release unzip jq rng-tools
      
      curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
      unzip awscliv2.zip
      ./aws/install
      rm -rf ./aws ./awscliv2.zip

      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      gpasswd -a ubuntu docker
      mkdir -p /etc/docker/

      if [ ! -f /etc/docker/daemon.json ]; then
        echo '{ "registry-mirrors": ["https://mirror.gcr.io"] }' > /etc/docker/daemon.json
      else
        jq '.["registry-mirrors"] += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > /etc/docker/daemon.tmp && mv /etc/docker/daemon.tmp /etc/docker/daemon.json
      fi

      service docker restart

  - path: /home/ubuntu/cloud-init.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      export APP_NAME=${name}
      export APP_ENV=${env}

      aws ssm describe-parameters | jq -r '.Parameters[].Name' | grep "\/application\/$APP_NAME\/$APP_ENV" | sed "s/\/application.*$APP_ENV\///" | while read -r FILE; do
          mkdir -p $(dirname "$FILE");
          aws ssm get-parameter --name "/application/$APP_NAME/$APP_ENV/$FILE" --output text --with-decrypt --query 'Parameter.Value' | sed "s/###//g" > "$FILE";
      done

      source .envrc

      export INSTANCE_ID_SUBST=`wget http://169.254.169.254/latest/meta-data/instance-id -O- --timeout=5 --tries=1`
      [ -z "$INSTANCE_ID_SUBST" ] && export INSTANCE_ID_SUBST='{% raw %}{{.FullID}}{% endraw %}'
      echo "INSTANCE_ID_SUBST=$INSTANCE_ID_SUBST" >> .env

      [ -f secret.env ] && cat secret.env >> .env


      aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin "$AWS_ECR_BASE_URL"
      docker compose up -d

runcmd:
  - chown -R ubuntu:ubuntu /home/ubuntu
  - cd /home/ubuntu/
  {% if cookiecutter.aws_use_packer == 'n' %}
  - "[ -f ./installer.sh ] && ./installer.sh"
  {% endif %}
  - sudo -u ubuntu ./cloud-init.sh
